### ISSUE TITLE
Anymatch 3.1.3 represents a non backward compatible change and thus should increment the MAJOR version number.

### ISSUE THREAD

**Issue by seanmorris** [micromatch/anymatch#51]
Semver dictates that patch versions only fix issues, and do not add new functionality. It dictates that minor version incrementation represents an additional feature, with no breaking changes to existing APIs. It specifies that breaking, non-backward compatible changes should be reserved for updates that increment the major version only.

Anymatch@3.1.3 vs anymatch@3.1.2 handle filepaths completely differently. One will strip trailing paths while the other passes the right on through. This breaks the semver spec above.

An example of a major project that was broken by the above change is [brunch/brunch](https://github.com/brunch/brunch).

Please be aware of this when deciding which part of the version number to increment. The purpose of semver is to allow things like bugfixes and critical security updates to be rolled out in patches so that the prefix sigil "^" in package.json can be used with confidence.

If changes like this are rolled out in patch versions, developers will lose confidence in the automatic update structure of npm, and security holes will remain open in places they otherwise would not.

Please enforce semver when rolling out new releases. Its the responsible thing to do.

**Comment by phated** [comment]
Please don't try to lecture **me** or **Paul** (brunch is literally his project) about semver. As you can see in [the commit](https://github.com/micromatch/anymatch/commit/24c4b51b3f3cc8825506060a5e8cebf703d23d0f), this didn't change any tests and just added tests to show where the bug was. When a project relies on an untested case, that is actually a *bug*, you can't be certain about semver incompatibles.

As you noted in your linked PR, the problem was in the normalization of paths before being passed to this library: globs and paths **are not the same**.

It stinks that this broke you, but that is not a reason to come into a project and lecture folks.

**Comment by seanmorris** [comment]
I understand your point of view but I don't think that `npm update` should cause a function call on a dependency to change from returning false to true, given the same input. I feel its a bit dangerous and will compromise confidence in the update mechanism as a whole.

I'm sorry you disagree with me on this topic.

**Comment by seanmorris** [comment]
Also, if you can reach out to Paul about https://github.com/brunch/brunch/pull/1891, that would be great.
